// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzfetjnpyflkmnccamcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ZmV0am5weWZsa21uY2NhbWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDc3NDYsImV4cCI6MjA2NDg4Mzc0Nn0.JFp5FBoj2Zp8zS4IB2f0z7E-Dl8Gpk_byCEAuO4aJ_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);